# -*- coding: utf-8 -*-
{
    'name': 'Vendor Onboarding',
    'version': '16.0.1.0.0',
    'summary': """Vendor onboarding module""",
    'description': """ This module contains to onboard new vendors """,
    'category': 'Human Resources/Vendor',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['qwqer_base','account_base', 'fleet_ftl'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/vendor_lead_groups.xml',
        'security/vendor_lead_user_rule.xml',
        'security/ir.model.access.csv',
        'data/vendor_lead_mail_template.xml',
        'views/vendor_lead_view.xml',
        'views/partner_segment_view.xml',
        'views/partner_service_type_view.xml',
        'views/res_partner_view.xml',
        'views/vendor_lead_user_action_history_view.xml',
    ],
    'images': [''],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
