from . import work_order
from . import batch_trip_ftl
from . import trip_summary_ftl
from . import account_move
from . import partner_segment
from . import res_company_inherit
from . import res_config_settings
from . import vehicle_contract
from . import ftl_user_action_history
from . import account_payment
from . import res_partner
from . import customer_balance_summary