# -*- coding: utf-8 -*-
{
    'name': 'Fleet Management Extend',
    'version': '16.0.1.0.0',
    'summary': """Fleet module extended""",
    'description': """ This module contains modifications done in fleet module""",
    'category': 'Human Resources/Fleet',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['base', 'fleet', 'account', 'qwqer_base', 'delivery'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/fleet_management_group.xml',
        'security/fleet_contract_groups.xml',
        'security/fleet_contract_rules.xml',
        'security/ir.model.access.csv',
        'data/fleet_cron.xml',
        'data/fleet_sequence.xml',
        'data/fleet_email_template.xml',
        'wizard/vehicle_contract_action_history_wizard.xml',
        'views/res_partner_views.xml',
        'views/vehicle_vehicle_views.xml',
        'views/vehicle_vehicle_contract.xml',
        'views/partner_service_type_view.xml',
        'views/vehicle_pricing_line_view.xml',
        'views/res_config_settings_view.xml',
        'views/menu.xml',
        'views/vehicle_vehicle_type_view.xml',
        'views/partner_segment.xml',
        'views/product_template.xml',
    ],
    'images': [''],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
