from . import user_comments
from . import user_action_history
from . import document_type
from . import customer_onboard
from . import potential_orders
from . import pricing_plan
from . import res_partner
from . import hr_employee
from . import invoice_frequency
from . import customer_additional_charges
from . import settlement_time
from . import source_type
from . import crm_lead
