# -*- coding: utf-8 -*-
{
    'name': 'HR Expense Extended',
    'version': '16.0.1.0.0',
    'summary': """HR Expense Extended""",
    'description': """ This module contains modifications done in hr_expense module""",
    'category': 'Expense',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['base', 'account', 'account_base','hr','hr_expense','base_accounting_kit','qwqer_base'],
    'website': 'https://qwysoft.com/',
    'data': [
        "security/expense_claim_groups.xml",
        "security/ir_rule.xml",
        "security/ir.model.access.csv",
        "data/expense_sequence.xml",
        "wizard/hr_expense_claim_comment_wiz.xml",
        "wizard/expense_claim_payment_wizard.xml",
        "wizard/update_expense_manager_wizard.xml",
        "views/hr_expense_claim.xml",
        "views/account_payment_view.xml",
        "views/travel_mode_view.xml",
        "views/product_product_view.xml",
    ],
    'images': [],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
