{
    'name': "Delivery Base",
    'version': '16.0.1.0.0',
    'summary': """Base module """,
    'description': """ This module contains additional charges and pricing plans for delivery""",
    'category': 'Delivery',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    # any module necessary for this one to work correctly
    'depends': ['base','sale_extended','payment_cashfree'],
    'website': 'https://qwysoft.com/',
    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'security/rules.xml',
        'data/customer_age_scheduler_data.xml',
        'data/delivery_merchant_payout_cashfree_status.xml',
        'data/sequence.xml',
        'data/delivery_merchant_payout_mail_template.xml',
        'data/delivery_merchant_payout_mail_template.xml',
        'report/merchant_payout_line_xlsx_view.xml',
        'wizard/re_init_payment_view.xml',
        'views/partner_service_type_view.xml',
        'views/res_partner.xml',
        'views/charge_type.xml',
        'views/age_configuration_view.xml',
        'views/state_journal_view.xml',
        'views/merchant_account_config.xml',
        'views/delivery_merchant_payout.xml',
    ],
    'images': ["static/description/icon.png"],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
