from . import account_move_line
from . import driver_vehicle_category
from . import driver_document_type
from . import holiday_incentive_details
from . import driver_shift_type
from . import hr_department
from . import driver_payout_accounting_config
from . import driver_payout_plans
from . import driver_payout_plans_config
from . import employee_shift_type
from . import res_partner
from . import driver_veicle_documents
from . import hr_employee
from . import hr_attendance
from . import driver_payout
from . import account_account
from . import hr_job
from . import account_journal
from . import account_move
from . import res_config_settings
from . import driver_payin
from . import driver_batch_payout
from . import driver_payout_date_config
from . import application_driver_balance
from . import driver_batch_payout_lines
from . import payout_status_update
from . import sale_order
from . import hr_employee_documents
from . import employee_asset_type
from . import employee_assets
from . import nominee_type
from . import employee_insurance
from . import account_payment_register