from . import vehicle_vehicle
from . import vehicle_vehicle_contract
from . import res_partner
from . import account_move
from . import agreement_attchment
from . import vehicle_contract_action_history
from . import partner_vehicle_pricing
from . import fleet_vehicle_inherit
from . import vehicle_pricing
from . import vehicle_pricing_line
from . import partner_service_type
from . import res_config_settings
from . import vehicle_type
from . import partner_segment
from . import product_template
