# -*- coding: utf-8 -*-
{
    'name': 'Fleet FTL',
    'version': '16.0.1.0.02',
    'summary': """Fleet module extended""",
    'description': """ This module contains modifications done in fleet module""",
    'category': 'Human Resources/Fleet',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['base', 'web', 'account', 'fleet', 'fleet_extend', 'account_base', 'report_xlsx', 'delivery', 'qwy_google_geo_locator', 'base_accounting_kit'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/ftl_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ftl_sequence.xml',
        'data/revenue_report_cron.xml',
        'data/ftl_wo_email_template.xml',
        'data/ftl_trip_email_template.xml',
        'data/monthly_revenue_report_email_template.xml',
        'data/daily_revenue_report_email_template.xml',
        'wizard/wo_adv_payment_wizard_views.xml',
        'wizard/cost_analysis_report_wizard_view.xml',
        'views/res_partner_views.xml',
        'views/partner_segment.xml',
        'views/work_order_view.xml',
        'views/trip_summary_ftl.xml',
        'views/account_move_view.xml',
        'views/batch_trip_ftl_views.xml',
        'views/account_payment_view.xml',
        'views/ftl_user_action_history.xml',
        'views/res_config_settings_view.xml',
        'views/vehicle_contract_view.xml',
        'views/customer_balance_summary.xml',
        'wizard/cost_analysis_report_wizard_view.xml',
        'report/report_xlsx.xml',
        'report/account_invoice_template_inherited.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'fleet_ftl/static/src/xml/**/*',
            'fleet_ftl/static/src/css/button_style.css'
        ],
    },
    'images': [],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
