{
    'name': 'KPI Reports',
    'version': '16.0.1.0.04',
    'category': 'KPI Reports',
    'summary': 'KPI Reports module',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'description': """ This module contains KPI Reports.""",
    'website': 'https://qwysoft.com/',
    'depends': ['sale','user_access', 'account','sale_extended','qshop_base'],
    'data': [
        'security/ir.model.access.csv',
        'security/menu_access.xml',
        'report/sale_order_report_xl.xml',
        'report/revenue_report_xl.xml',
        'report/invoice_summary_report.xml',
        'report/sales_person_summary_report.xml',
        'wizard/sale_order_report_wizard.xml',
        'wizard/invoice_summary_report_wizard.xml',
        'wizard/sales_person_summary_report_wizard.xml',
        'wizard/revenue_report_xl_wizard.xml',
        'views/menu_items.xml',
        'views/sale_analysis_report.xml',
        'views/average_cost_per_customer_analysis.xml',
        'views/qwqer_shop_merchant_analysis_report.xml',
        'views/delivery_merchant_analysis_report.xml',
        'views/invoice.xml',
        'views/monthly_segment_wise_customer_count.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
