{
    "name": "CRM Lead Management",
    'version': '16.0.1.0.01',
    'summary': """crm module customization""",
    'description': """ This module contains modifications done in crm module""",
    'category': 'CRM Lead Management',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    "depends": ["base","crm","account","sale_crm","sales_team","contacts","mail",'report_xlsx',"fleet_extend",'account_base',
                "delivery_base", "qshop_base"],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/crm_config_qroups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/crm_quotation_mail_template.xml',
        'data/crm_stages.xml',
        'report/crm_report.xml',
        'views/followup_status_views.xml',
        'views/crm_leads.xml',
        'views/crm_stage_views.xml',
        'views/delivery_type_view.xml',
        'views/followup_status_views.xml',
        'views/crm_bulk_import.xml',
        'views/competition_master.xml',
        'views/menu_item.xml',
    ],
    'images': [''],
    'license': 'LGPL-3',
    'installable': True,
    'post_init_hook': 'post_init_hook',
    'auto_install': False,
    'application': False,
}

