from . import sales_region
from . import sales_zone
from . import res_country
from . import hr_employee
from . import res_partner
from . import state_journal
from . import account_move
from . import partner_service_type
from . import partner_segment
from . import res_users
from . import partner_document
from . import res_state_city
from . import item_category
from . import product_lines
