{
    "name": "Sales Person Target",
    'version': '16.0.1.0.0',
    'summary': """Sales Person Target Setting and Analysing """,
    'description': """ This module contains Sales Person Target Settings and Reports""",
    'category': 'Sales Person Target',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    "depends": ['base', 'fleet_ftl', 'fleet_urban_haul', 'fleet_extend','account'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/target_group.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron_data.xml',
        'data/target_email_templates.xml',
        'views/payments.xml',
        'views/target_configuration.xml',
        'views/sales_person_target_list_view.xml',
        'views/menu_items.xml',
    ],
    'images': [''],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
