# -*- coding: utf-8 -*-
{
    'name': 'QWQER Base Features',
    'version': '16.0.1.0.0',
    'summary': """base """,
    'description': """ This module contains modifications done in accounting module""",
    'category': 'Accounting',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['base','hr','contacts', 'account', 'l10n_in'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/hr_department_data.xml',
        'data/hr_job_data.xml',
        'data/partner_segment_data.xml',
        'views/sales_region_views.xml',
        'views/sales_zone_views.xml',
        'views/res_country_view.xml',
        'views/hr_employee.xml',
        'views/res_partner_views.xml',
        'views/account_move.xml',
        'views/state_journal.xml',
        'views/partner_service_type_view.xml',
        'views/partner_segment_view.xml',
        'views/res_users_views.xml',
        'views/res_state_city_view.xml',
        'views/item_category_view.xml',
        'views/product_lines_views.xml',
        'wizard/warning_message_popup_wizard_view.xml',
        'wizard/hr_emp_upd_wizard_view.xml',
        'views/menu.xml',
        'views/nav_bar_style.xml'
    ],
    'images': ["static/description/icon.png"],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
