# -*- coding: utf-8 -*-
{
    'name': 'QWQER Account Base',
    'version': '16.0.1.0.0',
    'summary': """base """,
    'description': """ This module contains modifications done in accounting module """,
    'category': 'Accounting',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['account','qwqer_base','l10n_in','qwqer_api_base','hr_expense','sale','stock'],
    'website': 'https://qwysoft.com/',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/tds_report.xml',
        'data/sequence.xml',
        'data/account_tax_data.xml',
        'data/payment_mode_data.xml',
        'data/invoice_scheduler_info_clear.xml',
        'data/scheduler.xml',
        'views/account_move.xml',
        'views/account_tax.xml',
        'views/account_journal_view.xml',
        'views/account_move_line.xml',
        'views/bank_and_cash_view.xml',
        'views/menu.xml',
        'views/virtual_account_configuration_view.xml',
        'views/virtual_account_settlement_view.xml',
        'views/res_partner_view.xml',
        'views/res_company_view.xml',
        'views/payment_mode.xml',
        'views/customer_balance_summary.xml',
        'views/invoice_exception_log_view.xml',
        'views/invoice_post_scheduler_info.xml',
        'views/res_config_settings_views.xml',
        'views/hr_employee.xml',
        'views/ledger_balance_import_from_xlxs_view.xml',
        'wizard/tds_report_wizard_view.xml',
        'reports/account_invoice_service.xml',
        'wizard/aged_balance_import_wizard_view.xml'
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,

}