{
    'name': 'Customer Onboarding',
    'version': '16.0.1.0.02',
    'author': 'QWY Software PVT Ltd',
    'website': 'https://qwysoft.com/',
        'depends': ['crm_lead_management', 'fleet_extend','account_base'],
    'demo': [],
    'description': """
    Module for Customer onboarding processing
    """,
    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'data/onboarding_approval_mail.xml',
             'wizards/message_wizard_view.xml',
             'views/customer_onboard_view.xml',
             'views/send_for_approval_view.xml',
             'views/potential_orders_view.xml',
             'views/res_partner.xml',
             'views/hr_employee_views.xml',
             'views/invoice_frequency_views.xml',
             'views/settlement_time_view.xml',
             'views/source_type_views.xml',
             'views/crm_lead.xml',
             ],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'images': ["static/description/icon.jpeg"],
    'summary': 'Customer Onboarding',
    'category': '',
}
