# -*- coding: utf-8 -*-
{
    'name': 'Driver Management',
    'version': '16.0.1.0.0',
    'summary': """Driver Management""",
    'description': """ This module contains Driver Management for Delivery/Shop""",
    'category': 'Human Resources',
    'author': 'QWY Software PVT Ltd',
    'company': 'QWY Software PVT Ltd',
    'maintainer': 'QWY Software PVT Ltd',
    'depends': ['base','hr','mail','account','hr_attendance', 'qwqer_base', 'account_base','qwqer_api_base',
                'payment_cashfree', 'delivery_base'],
    'website': 'https://qwysoft.com/',
    'data': [
        'wizard/hr_emp_upd_wizard_views.xml',
        'wizard/send_verification_wizard.xml',
        'wizard/driver_payout_update_views.xml',
        'reports/payout_variable_update_sample_views.xml',
        'wizard/update_scheduled_action_wizard.xml',
        'wizard/reject_wiz.xml',
        'views/hr_employee.xml',
        'reports/cost_per_order_report.xml',
        'reports/de_productivity_report.xml',
        'reports/report_xlsx.xml',
        'security/security.xml',
        'data/driver_vehicle_category.xml',
        'data/driver_document_type.xml',
        'data/hr_employee_shift_type.xml',
        'data/driver_payout_status_scheduler.xml',
        'security/ir.model.access.csv',
        'data/payout_sequence.xml',
        'data/payout_cron.xml',
        'data/mail_template.xml',
        'data/driver_balance_cron.xml',
        'data/payout_plan_sequence.xml',
        'views/driver_payout.xml',
        'views/hr_department.xml',
        'views/driver_shift_type.xml',
        'views/holiday_incentive_details.xml',
        'views/driver_vehicle_category.xml',
        'wizard/update_driver_plan_wixard.xml',
        'wizard/reinitiate_payment.xml',
        'views/driver_payout_plans.xml',
        'views/driver_batch_payout.xml',
        'views/driver_payout_date_config.xml',
        'views/driver_payout_accounting_config.xml',
        'views/driver_document_type.xml',
        'views/employee_shift_type.xml',
        'views/hr_attendance.xml',
        'views/hr_job_views.xml',
        'views/account_account_view.xml',
        'views/account_move_line.xml',
        'views/account_journal_view.xml',
        'views/account_move.xml',
        'views/res_partner_view.xml',
        'views/res_config_settings_views.xml',
        'views/payout_status_update_view.xml',
        'views/driver_payin_view.xml',
        'views/driver_batch_payout_vendor.xml',
        'views/sales_region.xml',
        'views/application_driver_balance_view.xml',
        'views/driver_report.xml',
        'views/sale_order_form.xml',
        'wizard/hr_emp_upd_wizard_views.xml',
        'wizard/send_verification_wizard.xml',
        'wizard/driver_payout_plan_change_wizard.xml',
        'views/application_driver_balance_view.xml',
        'views/employee_asset_type.xml',
        'views/nominee_type.xml',
        'views/driver_batch_payout_lines.xml'
    ],
    'images': [],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
