name: CI/CD for Odoo Custom Addons

on:
  workflow_dispatch:
    branches:
      - development  # Trigger on changes to the development branch

jobs:
  deploy:
    name: Deploy Custom Addons to Odoo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Custom Addons
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

        - name: Fix Private Key Formatting
      run: |
        echo "${PRIVATE_KEY}" | awk '{gsub(/\\n/,"\n")}1' > private_key.pem
        chmod 600 private_key.pem

        echo "🔑 Adding the server to known_hosts..."
        mkdir -p ~/.ssh
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        echo "🛠 Connecting to the server and deploying the code..."
        ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SERVER_USER}@${SERVER_IP} << 'EOF'
          echo "📂 Navigating to /opt/odoo16/odoo16/custom_addons..."
          cd /opt/odoo16/odoo16/custom_addons

          echo "🔄 Pulling the latest code from GitHub..."
          git pull origin development

          echo "🔄 Restarting the Odoo service..."
          sudo systemctl restart odoo16.service
          echo "✅ Deployment completed successfully!"
        EOF
