name: CI/CD for Odoo Custom Addons

on:
  workflow_dispatch:
    branches:
      - development  # Trigger on changes to the main branch

jobs:
  deploy:
    name: Deploy Custom Addons to Odoo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Custom Addons
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "Saving the SSH private key..."
        echo "${PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        echo "Connecting to the server and deploying the code..."
        ssh -i private_key.pem ${SERVER_USER}@${SERVER_IP} << EOF
          echo "Navigating to /opt/odoo16/odoo16/custom_addons..."
          cd /opt/odoo16/odoo16/custom

          echo "Pulling the latest code from GitHub..."
          git pull https://github.com/sivaram2806/qwqer_16_fleet_dev.git


          echo "Restarting the Odoo service..."
          sudo systemctl restart odoo16.service
          echo "Deployment completed successfully!"
        EOF
